# Generated by Django 3.2 on 2021-10-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20211001_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
