# Generated by Django 3.2 on 2021-11-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterModelTable(
            name='note',
            table='notes',
        ),
    ]
